server:
  contextPath: null
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
  http:
      multipart:
        location: ..
  jackson:
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
  jpa: 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  datasource:
    url: jdbc:mysql://localhost/auth
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
file:
  upload-dir: ./uploads